[package]
name = "terrain_generation_and_visualization"
version = "0.1.0"
authors = ["gorilskij <43991400@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
num-traits = "0.2.8"
mint = "0.5.4"
ggez = "0.5.1"